name: Release
"on":
  push:
    branches:
    - main
  workflow_dispatch: null
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Create release draft
      uses: darioblanco/release-wizard@main
      with:
        draft: true
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        taskBaseUrl: null
        taskPrefix: null
        pushTag: false
        withV: true
