name: Release
"on":
  push:
    branches:
    - main
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Create release
        uses: darioblanco/release-wizard@main
        with:
          draft: true
          token: ${{ github.token }}
